-- 코드를 입력하세요
-- LIKE 연산자와 와일드카드 사용하기
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_INS
-- WHERE NAME LIKE 'El%' OR NAME LIKE '%el%' OR NAME LIKE '%el'
-- AND ANIMAL_TYPE='DOG';

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE UPPER(NAME) LIKE '%EL%'
AND ANIMAL_TYPE='Dog'
ORDER BY NAME;